project:
  type: book

execute:
  freeze: auto
  
book:
  title: "Longitudinal A4 & Gene Expression Project"
  author: "Hannah Klinger"
  date: "`r Sys.Date()`"
  chapters:
    - index.qmd
    - demographics.qmd
    - visualizations.qmd
    - model_summary.qmd
    - manhattan_plots.qmd
    - part: pacc_sensitivity_nosf.qmd
      chapters:
        - pacc_sensitivity_sexstratified.qmd
    - amyloid_sensitivity_nosf.qmd
    - part: bl_ptau_analyses_old.qmd
      chapters:
        - bl_ptau_sensitivity_treatvsplacebo.qmd


format:
  html:
    self-contained: true
    theme: cosmo
    number-sections: false

editor: visual


