project:
  type: book

execute:
  freeze: auto
  
book:
  title: "Longitudinal A4 & Gene Expression Project"
  author: "Hannah Klinger"
  date: "`r Sys.Date()`"
  chapters:
    - index.qmd
    - demographics.qmd
    - visualizations.qmd
    - model_summary.qmd
    - manhattan_plots.qmd
    - part: pacc_analyses.qmd
      chapters:
        - pacc_sensitivity_sexstratified.qmd
        - pacc_sensitivity_treatvsplacebo.qmd
    - amyloid_analyses.qmd
    - part: bl_ptau_analyses.qmd 
      chapters:
        - bl_ptau_sensitivity_treatvsplacebo.qmd
    - null_results.qmd

format:
  html:
    self-contained: true
    theme: cosmo
    number-sections: false

editor: visual


