project:
  type: book

execute:
  freeze: auto
  
book:
  title: "Longitudinal A4 & Gene Expression Project"
  author: "Hannah Klinger"
  date: "`r Sys.Date()`"
  chapters:
    - index.qmd
    - demographics.qmd
    - visualizations.qmd
    - model_summary.qmd
    - manhattan_plots.qmd


format:
  html:
    self-contained: true
    theme: cosmo
    number-sections: false

editor: visual


