---
title: "Sensitivity Analysis: A4 Treated vs Placebo"
---

```{r setup, include = FALSE, warning = FALSE, message = FALSE}
library(plyr)
library(nlme)
library(ggplot2)
library(sjPlot)
library(dplyr)
library(gtsummary)
library(flextable)
library(ggrepel)
library(readr)
library(DT)
library(tidyr)

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
theme_set(theme_bw())
```

```{r}
load(file = "~/Dropbox (Partners HealthCare)/Mabel/Longitudinal A4 & Gene Expression/New Data/RNAseqData_Autosomal_XLinked_100824.RData")

gene_names <- readRDS("~/Dropbox (Partners HealthCare)/Mabel/Longitudinal A4 & Gene Expression/New Data/A4_RNAseq_GeneNames_081424.rds")

load("~/Dropbox (Partners HealthCare)/Mabel/Longitudinal A4 & Gene Expression/Baseline pTAU Models/LME_pTAUTable_GeneE4_Models_2024-10-08.RData")
load("~/Dropbox (Partners HealthCare)/Mabel/Longitudinal A4 & Gene Expression/Baseline pTAU Models/LME_pTAUTable_GeneAb_Models_2024-10-08.RData")
load("~/Dropbox (Partners HealthCare)/Mabel/Longitudinal A4 & Gene Expression/Baseline pTAU Models/LME_pTAUTable_GeneSexAb_Models_2024-10-08.RData")

load("~/Dropbox (Partners HealthCare)/Mabel/Longitudinal A4 & Gene Expression/Baseline pTAU Models/LME_pTAUTable_GeneE4_Treat_Models_2024-11-14.RData")
load("~/Dropbox (Partners HealthCare)/Mabel/Longitudinal A4 & Gene Expression/Baseline pTAU Models/LME_pTAUTable_GeneAb_Treat_Models_2024-11-14.RData")
load("~/Dropbox (Partners HealthCare)/Mabel/Longitudinal A4 & Gene Expression/Baseline pTAU Models/LME_pTAUTable_GeneSexAb_Treat_Models_2024-11-14.RData")

load("~/Dropbox (Partners HealthCare)/Mabel/Longitudinal A4 & Gene Expression/Baseline pTAU Models/LME_pTAUTable_GeneE4_Placebo_Models_2024-11-14.RData")
load("~/Dropbox (Partners HealthCare)/Mabel/Longitudinal A4 & Gene Expression/Baseline pTAU Models/LME_pTAUTable_GeneAb_Placebo_Models_2024-11-14.RData")
load("~/Dropbox (Partners HealthCare)/Mabel/Longitudinal A4 & Gene Expression/Baseline pTAU Models/LME_pTAUTable_GeneSexAb_Placebo_Models_2024-11-14.RData")

```

```{r}
gene_names <- select(gene_names, gene = ensembl_gene_id, chromosome_name, external_gene_name)
```

# pTau \~ Gene x APOEe4

```{r}
pTAUTable_GeneE4_Treat <- select(pTAUTable_GeneE4_Treat, gene, treated_beta = beta, treated_se = se, treated_t = t, treated_p = p)
pTAUTable_GeneE4_Placebo <- select(pTAUTable_GeneE4_Placebo, gene, placebo_beta = beta, placebo_se = se, placebo_t = t, placebo_p = p)
pTAUTable_GeneE4_all <- pTAUTable_GeneE4 %>%
  select(-c(outcome)) %>%
  left_join(pTAUTable_GeneE4_Treat, by = "gene") %>%
  left_join(pTAUTable_GeneE4_Placebo, by = "gene") %>%
  left_join(gene_names, by = "gene") %>%
  filter(fdr_p < 0.05)

pTAUTable_GeneE4_all[,2:14] <- round(pTAUTable_GeneE4_all[,2:14],4)
```

```{r}
pTAUTable_GeneE4_all$treated_beta_compare <- ifelse(sign(pTAUTable_GeneE4_all$beta) == sign(pTAUTable_GeneE4_all$treated_beta), 0, 1)

pTAUTable_GeneE4_all$placebo_beta_compare <- ifelse(sign(pTAUTable_GeneE4_all$beta) == sign(pTAUTable_GeneE4_all$placebo_beta), 0, 1)

pTAUTable_GeneE4_all$overall_compare <- ifelse(pTAUTable_GeneE4_all$treated_beta_compare == 1 | pTAUTable_GeneE4_all$placebo_beta_compare == 1, 1, 0)
```

```{r}
datatable(pTAUTable_GeneE4_all,
          filter = "top",
          rownames = FALSE,
          extensions = c('Buttons'),
          options = list(dom = 'Btip',
                         buttons = c('copy', 'csv'),
                         pageLength = 15,
                         columnDefs = list(list(className = 'dt-center', targets = 0:16)))) %>%
  formatRound(columns = c("beta","se", "t", "p", "fdr_p"), digits = 4) %>%
  formatStyle("overall_compare", backgroundColor = styleEqual(c(0, 1), c('grey96', 'yellow')))

```

# pTau \~ Gene x Amyloid

```{r}
pTAUTable_GeneAb_Treat <- select(pTAUTable_GeneAb_Treat, gene, treated_beta = beta, treated_se = se, treated_t = t, treated_p = p)
pTAUTable_GeneAb_Placebo <- select(pTAUTable_GeneAb_Placebo, gene, placebo_beta = beta, placebo_se = se, placebo_t = t, placebo_p = p)
pTAUTable_GeneAb_all <- pTAUTable_GeneAb %>%
  select(-c(outcome)) %>%
  left_join(pTAUTable_GeneAb_Treat, by = "gene") %>%
  left_join(pTAUTable_GeneAb_Placebo, by = "gene") %>%
  left_join(gene_names, by = "gene") %>%
  filter(fdr_p < 0.05)

pTAUTable_GeneAb_all[,2:14] <- round(pTAUTable_GeneAb_all[,2:14],4)

pTAUTable_GeneAb_all$treated_beta_compare <- ifelse(sign(pTAUTable_GeneAb_all$beta) == sign(pTAUTable_GeneAb_all$treated_beta), 0, 1)

pTAUTable_GeneAb_all$placebo_beta_compare <- ifelse(sign(pTAUTable_GeneAb_all$beta) == sign(pTAUTable_GeneAb_all$placebo_beta), 0, 1)

pTAUTable_GeneAb_all$overall_compare <- ifelse(pTAUTable_GeneAb_all$treated_beta_compare == 1 | pTAUTable_GeneAb_all$placebo_beta_compare == 1, 1, 0)
```

```{r}
datatable(pTAUTable_GeneAb_all,
          filter = "top",
          rownames = FALSE,
          extensions = c('Buttons'),
          options = list(dom = 'Btip',
                         buttons = c('copy', 'csv'),
                         pageLength = 15,
                         columnDefs = list(list(className = 'dt-center', targets = 0:16)))) %>%
  formatRound(columns = c("beta","se", "t", "p", "fdr_p"), digits = 4) %>%
  formatStyle("overall_compare", target = "row", backgroundColor = styleEqual(c(0, 1), c('grey96', 'yellow')))

```

# pTau \~ Gene x Amyloid x Sex

```{r}
pTAUTable_GeneSexAb_Treat <- select(pTAUTable_GeneSexAb_Treat, gene, treated_beta = beta, treated_se = se, treated_t = t, treated_p = p)
pTAUTable_GeneSexAb_Placebo <- select(pTAUTable_GeneSexAb_Placebo, gene, placebo_beta = beta, placebo_se = se, placebo_t = t, placebo_p = p)
pTAUTable_GeneSexAb_all <- pTAUTable_GeneSexAb %>%
  select(-c(outcome)) %>%
  left_join(pTAUTable_GeneSexAb_Treat, by = "gene") %>%
  left_join(pTAUTable_GeneSexAb_Placebo, by = "gene") %>%
  left_join(gene_names, by = "gene") %>%
  filter(fdr_p < 0.05)

pTAUTable_GeneSexAb_all[,2:14] <- round(pTAUTable_GeneSexAb_all[,2:14],4)

pTAUTable_GeneSexAb_all$treated_beta_compare <- ifelse(sign(pTAUTable_GeneSexAb_all$beta) == sign(pTAUTable_GeneSexAb_all$treated_beta), 0, 1)

pTAUTable_GeneSexAb_all$placebo_beta_compare <- ifelse(sign(pTAUTable_GeneSexAb_all$beta) == sign(pTAUTable_GeneSexAb_all$placebo_beta), 0, 1)

pTAUTable_GeneSexAb_all$overall_compare <- ifelse(pTAUTable_GeneSexAb_all$treated_beta_compare == 1 | pTAUTable_GeneSexAb_all$placebo_beta_compare == 1, 1, 0)
```

```{r}
datatable(pTAUTable_GeneSexAb_all,
          filter = "top",
          rownames = FALSE,
          extensions = c('Buttons'),
          options = list(dom = 'Btip',
                         buttons = c('copy', 'csv'),
                         pageLength = 15,
                         columnDefs = list(list(className = 'dt-center', targets = 0:16)))) %>%
  formatRound(columns = c("beta","se", "t", "p", "fdr_p"), digits = 4) %>%
  formatStyle("overall_compare", target = "row", backgroundColor = styleEqual(c(0, 1), c('grey96', 'yellow')))

```
