---
title: "Visualizations"
---

```{r setup, include = FALSE, warning = FALSE, message = FALSE}
library(plyr)
library(nlme)
library(ggplot2)
library(sjPlot)
library(dplyr)
library(gtsummary)
library(flextable)
library(ggrepel)
library(readr)
library(DT)
library(tidyr)

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
theme_set(theme_bw())
```

```{r}
load(file = "~/Dropbox (Partners HealthCare)/Mabel/Longitudinal A4 & Gene Expression/New Data/RNAseqData_Autosomal_XLinked_wDose_120424.RData")
```

```{r}
bl_amyloid <- rna %>%
  filter(!is.na(suvr_cer)) %>%
  group_by(BID) %>%
  arrange(BID, ab_time) %>%
  slice(1) %>%
  select(BID, ab_age, suvr_cer,  overall_score)

bl_tau <- rna %>%
  filter(!is.na(MTL)) %>%
  group_by(BID) %>%
  arrange(BID, tau_time) %>%
  slice(1) %>%
  select(BID, tau_age, MTL, NEO)

bl_ptau <- rna %>%
  filter(!is.na(ptau217)) %>%
  group_by(BID) %>%
  arrange(BID, ptau_time) %>%
  slice(1) %>%
  mutate(ptau217 = case_when(
    ptau217 == "" ~ NA,
    TRUE ~ ptau217)) %>%
  select(BID, ptau_age, ptau217)

baseline <- rna %>%
  filter(!is.na(PACC)) %>%
  group_by(BID) %>%
  arrange(BID, pacc_time) %>%
  slice(1) %>%
  select(BID:PACC, pacc_age) %>%
  left_join(bl_amyloid, by = "BID") %>%
  left_join(bl_tau, by = "BID") %>%
  left_join(bl_ptau, by = "BID") %>%
  mutate(Cohort = case_when(
    SUBSTUDY == "A4" ~ "A4",
    TRUE ~ "LEARN/SF"
  ))
```

# Baseline Distributions

## PACC

```{r}
ggplot(baseline, aes(x = PACC)) + 
  geom_histogram(fill = "steelblue", color = "white") + 
  labs(
    x = "Baseline PACC",
    y = "Frequency",
    title = "Distribution of Baseline PACC",
    subtitle = paste0("N = ", nrow(subset(baseline, !is.na(PACC))))
  )
```

## Amyloid

```{r}
ggplot(baseline, aes(x = suvr_cer)) + 
  geom_histogram(fill = "steelblue", color = "white") + 
  labs(
    x = "Baseline Amyloid",
    y = "Frequency",
    title = "Distribution of Baseline Amyloid",
    subtitle = paste0("N = ", nrow(subset(baseline, !is.na(suvr_cer))))

  )
```

## MTL Tau

```{r}
ggplot(baseline, aes(x = MTL)) + 
  geom_histogram(binwidth = 0.05, fill = "steelblue", color = "white") + 
  labs(
    x = "Baseline MTL",
    y = "Frequency",
    title = "Distribution of Baseline MTL Tau",    
    subtitle = paste0("N = ", nrow(subset(baseline, !is.na(MTL))))

  )
```

## NEO Tau

```{r}
ggplot(baseline, aes(x = NEO)) + 
  geom_histogram(binwidth = 0.05, fill = "steelblue", color = "white") + 
  labs(
    x = "Baseline NEO",
    y = "Frequency",
    title = "Distribution of Baseline NEO Tau",
    subtitle = paste0("N = ", nrow(subset(baseline, !is.na(NEO))))
  )
```

## p-tau217

```{r}
ggplot(baseline, aes(x = as.numeric(ptau217))) + 
  geom_histogram(fill = "steelblue", color = "white") + 
  labs(
    x = "Baseline p-tau217",
    y = "Frequency",
    title = "Distribution of Baseline p-tau217",
    subtitle = paste0("N = ", nrow(subset(baseline, !is.na(ptau217))))

  )
```

# Longitudinal Trajectories

## PACC

```{r}
ggplot(rna, aes(x = pacc_time, y = PACC)) + 
  geom_line(aes(group = BID)) + 
  labs(
    x = "Time (years)",
    y = "PACC",
    title = "Longitudinal PACC"
    )
```

# Longitudinal Amyloid

```{r}
ggplot(rna, aes(x = ab_time, y = suvr_cer)) + 
  geom_line(aes(group = BID)) + 
  labs(
    x = "Time (years)",
    y = "Amyloid",
    title = "Longitudinal Amyloid"
    )
```

## MTL Tau

```{r}
ggplot(rna, aes(x = tau_time, y = MTL)) + 
  geom_line(aes(group = BID)) + 
  labs(
    x = "Time (years)",
    y = "Medial Temporal Lobe Tau",
    title = "Longitudinal MTL Tau"
    )
```

## NEO Tau

```{r}
ggplot(rna, aes(x = tau_time, y = NEO)) + 
  geom_line(aes(group = BID)) + 
  labs(
    x = "Time (years)",
    y = "Neocortical Tau",
    title = "Longitudinal NEO Tau"
    )
```

## p-tau217

```{r}
ggplot(rna, aes(x = ptau_time, y = as.numeric(ptau217))) + 
  geom_line(aes(group = BID)) + 
  labs(
    x = "Time (years)",
    y = "p-tau217",
    title = "Longitudinal p-tau217"
    )
```
